name: TopMoneyNPC
main: RhaxZDev\NPCTop\Main
version: 1
api: [4.0.0]
author: RhaxDev

permissions:
  cmd.topnpc:
    default: op
    description: Allows to Spawn TopNPC

commands:
  topnpc:
    description: TopMoneyNPC!
    permission: cmd.topnpc